name: EpicAnchors
description: EpicAnchors
version: 1
depend: [Arconix]
main: com.songoda.epicanchors.EpicAnchorsPlugin
author: songoda
api-version: 1.13
commands:
  EpicAnchors:
    description: I have no idea.
    default: true
    aliases: [ea]
    usage: /<command> [reload]